server:
  port: 8080
spring:
  application:
    name: "test-app"
  user-command:
    find-by: "user.find"
    routing-key: "user.save"
  rabbitmq:
    port: 5672
    host: "localhost"
    username: "guest"
    password: "guest"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
